version: '2'
services:
  order:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - .:/usr/src/app/node_modules
    ports:
      - "8001:8001"
    depends_on:
      - mariadb
    environment:
      DATABASE_URL: mariadb://'dev'@'%'/order
    networks:
      - default
      - payments_default
    external_links:
      - payments_web_1:payments.local
  mariadb:
    image: mariadb:10.7.1
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678@Abc
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: order
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
  #   driver: local
networks:
  payments_default:
    # external: true